spring:
  datasource:
    url: jdbc:mysql://10.211.55.4:3306/bos?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  mvc:
    view:
      prefix: /WEB-INF/pages/
      suffix: .jsp

mybatis:
  mapperLocations: classpath*:cn/itcast/bos/dao/*.xml
  # 配置类型别名
  typeAliasesPackage: cn.itcast.bos.domain
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  # 加载全局的配置文件
  configLocation: classpath:SqlMapConfig.xml
